### PR TITLE
feat!: Simplify use of the all_ports argument

### PR DESCRIPTION
**Pull request by colereynolds**
Today, the `ports` argument is required and no mention of exclusivity between the `ports` and `all_ports` argument is mentioned in the variable description or Terraform Registry docs for this module. If someone wants to use the `all_ports` argument, they have to go through a process of trial and error to figure out what value to pass to the `ports` argument in order to successfully deploy the forwarding rule. I'm proposing to make the `ports` argument optional and set the default value to `null`, which is the only value the backend API will accept to deploy the forwarding rule when `all_ports` is set to `true`.

I can't find where to update the Terraform Registry docs for this module. Adding more detail around the mutual exclusivity of the `ports` and `all_ports` arguments[1] would help users understand that only one of the two should be used, if someone could make time to create an issue for that, please.

[1] https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_forwarding_rule.html#all_ports

### CODE REVIEW

**Comment by imrannayer** [comment]
@colereynolds since we are changing default behavior it has to be a breaking change. Can you plz add a document mentioning this behavior change in [doc](https://github.com/terraform-google-modules/terraform-google-lb-internal/tree/master/docs) folder? use [this doc](https://github.com/terraform-google-modules/terraform-google-lb-internal/blob/master/docs/upgrading_to_lb_internal_v2.0.md) as example. Create one for version 6.0.

**Comment by imrannayer** [comment]
@colereynolds r u still working on this?

**Comment by colereynolds** [comment]
@imrannayer Yes. I haven't forgotten about this. I have been in a very busy season but things are getting back to normal. I will make time to do this sometime this week.

**Comment by colereynolds** [comment]
@imrannayer - Give this another look when you get a few. I made quite a few tweaks to update the README with a working example too.

**Review by imrannayer — APPROVED** [review]

**Pull request merged**
