### PR TITLE
fix!: Change default balancing_mode to CONNECTION for backends

### PR DESCRIPTION
**Pull request by graham-faulkner-geotab**

### CODE REVIEW

**Comment by imrannayer** [comment]
@graham-faulkner-geotab can u plz add docs upgrade to v7 in [docs folder](https://github.com/terraform-google-modules/terraform-google-lb-internal/tree/master/docs) and mention that this release is backward incompatible and changes default value of balancing_mode?

**Review by imrannayer — APPROVED** [review]

**Comment by graham-faulkner-geotab** [comment]
thank you @imrannayer

**Pull request merged**
