### PR TITLE
Add forwarding_rule id to output

### PR DESCRIPTION
**Pull request by tnguyen14**
I need to have access to the forwarding_rule ID

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by morgante — APPROVED** [review]

**Comment by tnguyen14** [comment]
Thanks for the merge @morgante. When will it be released? And will there be a 0.12-compatible version, or it will only be for 0.13? I'm asking because we're currently using 0.12. We could upgrade to 0.13, but wanna check if we need to do that.

**Comment by morgante** [comment]
@tnguyen14 Releases are approximately every 2 weeks.

We will not be doing a 0.12 version. 0.12 is pretty old at this point and I highly encourage upgrading.

**Comment by tnguyen14** [comment]
@morgante thanks. The last release was 22 days ago. When will the next release be cut?

**Comment by morgante** [comment]
@tnguyen14 Your change has only been merged for a few hours, so I do ask for some patience.

Expect a new release to be cut sometime next week.

**Comment by tnguyen14** [comment]
@morgante any chance a new release will be cut soon?

**Pull request merged**
